name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    name: Maven Setup
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Setup Project
        run: mvn package install
      - name: Maven Information
        run: mvn dependency:tree

  build:
    needs: setup
    strategy:
      matrix:
        java-version: [17, 18]

    runs-on: ubuntu-latest
    name: Build Java ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build Project
        run: mvn clean install
